version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vokra-import"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gdnuf216ck0j"
s3_prefix = "vokra-import"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
