AWSTemplateFormatVersion: 2010-09-09
Description: >-
  vokra-import-lambda

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ImportShelterluv:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          API_KEY: !Ref ApiKey
      Description: A Lambda function that imports cats, people and events from Shelterluv API into a Dgraph database
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: src/handlers/import-shelterluv.scheduledEventImportShelterluvHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
      MemorySize: 256
      Timeout: 600

Parameters:
  ApiKey:
    Type: String
